- name: Setup Nginx Reverse Proxy
  hosts: nginx_reverse_proxies
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        update_cache: true
        name: nginx

    - name: Copy configuration
      ansible.builtin.copy:
        src: ../templates/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"
